// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteHistory(arg1) {
  return window['go']['main']['HistoryService']['DeleteHistory'](arg1);
}

export function ListHistory() {
  return window['go']['main']['HistoryService']['ListHistory']();
}

export function SaveHistory(arg1) {
  return window['go']['main']['HistoryService']['SaveHistory'](arg1);
}
