// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteHistory(arg1:string):Promise<void>;

export function ListHistory():Promise<Array<main.HistoryEntry>>;

export function SaveHistory(arg1:main.HistoryEntry):Promise<main.HistoryEntry>;
