// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExtractUsedKeys(arg1) {
  return window['go']['main']['JqService']['ExtractUsedKeys'](arg1);
}

export function InferSchema(arg1) {
  return window['go']['main']['JqService']['InferSchema'](arg1);
}

export function RunQuery(arg1, arg2) {
  return window['go']['main']['JqService']['RunQuery'](arg1, arg2);
}
