// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ExtractUsedKeys(arg1:string):Promise<Array<string>>;

export function InferSchema(arg1:string):Promise<Array<main.SchemaNode>>;

export function RunQuery(arg1:string,arg2:string,arg3:boolean):Promise<main.RunResult>;
