// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteSaved(arg1) {
  return window['go']['main']['SavedService']['DeleteSaved'](arg1);
}

export function ListSaved() {
  return window['go']['main']['SavedService']['ListSaved']();
}

export function SaveItem(arg1) {
  return window['go']['main']['SavedService']['SaveItem'](arg1);
}
