// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteSaved(arg1:string):Promise<void>;

export function ListSaved():Promise<Array<main.SavedItem>>;

export function SaveItem(arg1:main.SavedItem):Promise<main.SavedItem>;
